swagger: '2.0'
info:
  description: This is an API to valide a password for the backend challenge case
  version: 1.0.0
  title: Validate Password API
  contact:
    email: helio.ortega.neto@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /v1/validate/password:
    post:
      summary: validates a password
      operationId: validatePassword
      description: attempts to validate a password via Regex and returns a boolean for validity and a list of validation errros
        found in the password
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: validatePasswordRequestModel
          description: Object with the password to validate
          schema:
            $ref: '#/definitions/ValidatePasswordRequestModel'
      responses:
        200:
        description: Object containing a boolean for password validity and a list of validation errors.
        content:
          application/json:
            schema:
              type: object
              items:
                $ref: '#/definitions/ValidatePasswordResponseModel'
        400:
          description: invalid input, object invalid
definitions:
  ValidatePasswordRequestModel:
    type: object
    required:
      - password
    properties:
      password:
        type: string
        format: password
        example: AbTp9!foA
  ValidatePasswordResponseModel:
    properties:
      isValid:
        type: boolean
        example: false
      errorList:
        type: array
        items:
          type: string
          example: ["Error", "Error2"]
host: virtserver.swaggerhub.com
basePath: /HelioOrtega/validatepassword/1.0.0
schemes:
  - https